on:
  workflow_dispatch:
  pull_request:
 
 
jobs:
  FoD-SAST-Scan:
    # Use the appropriate runner for building your source code.
    # TODO: Use a Windows runner for .NET projects that use msbuild. Additional changes to RUN commands will be required to switch to Windows syntax.
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write
 
    steps:
      - name: Check out source code
        uses: actions/checkout@v4
      - name: Run Fortify on Demand SAST & SCA Scan
        uses: fortify/github-action@v1
        with:
          sast-scan: true
          debricked-sca-scan: true
        env:
          FOD_URL: ${{secrets.FOD_URL}}
          FOD_TENANT: ${{secrets.FOD_TENANT}}
          FOD_CLIENT_ID: ${{secrets.FOD_CLIENT_ID}}
          FOD_CLIENT_SECRET: ${{secrets.FOD_CLIENT_SECRET}}
          FOD_RELEASE: "Test Git Action:${{ github.ref_name }}"
          DO_SETUP: true
          SETUP_EXTRA_OPTS: --use-aviator
          DO_WAIT: true
          DO_POLICY_CHECK: true
          DO_JOB_SUMMARY: true
